"""B1 - Python code execution.

The b1-codeexec-worker exposes POST /run {code, timeout}
returning {exit_code, stdout, stderr, wall_ms}.

We feed it a corpus of HumanEval + MBPP-sanitized canonical solutions
(plus their assert-style test cases). Each snippet is a self-contained
program that exits 0 on success, non-zero on assertion failure - which
mirrors how a real Agentic-RL sandbox verifies an LLM-generated patch.

Workload model is time-driven (run for `duration_sec` at the requested
concurrency, sample throughput / latency / resource), so corpus size
only affects coverage and P99 stability, not wall-clock duration.

Load is generated by N child processes (one per orchestrator vCPU by
default). Single-loop client was the binding constraint at c>=64 -
asyncio loop saturated at ~1 core just dispatching httpx requests +
parsing JSON responses, leaving the worker container's 16 cores half
idle while client-side latency ballooned (p99 4-5 sec at c=128).
With multi-process load gen, client distributes work across all
orchestrator vCPUs and the worker container actually runs out of CPU.
"""

from __future__ import annotations

import asyncio
import logging
import random
import time

import httpx

from config import Config
from metrics import ResourceSampler
from .b1_corpus import load_corpus
from .base import BenchmarkResult, Runner, cost_block, schedule_sampler_reset
from .multiproc import drive_load_mp

log = logging.getLogger(__name__)

# Per-snippet timeout (seconds). A handful of HumanEval tests touch
# brute-force / large-input edge cases, so 5s is too tight; 10s is
# conservative but still bounds long-tail.
SNIPPET_TIMEOUT = 10


# Module-level worker factory - must be picklable for multi-process
# spawn. Each child process gets its own httpx.AsyncClient and walks
# the corpus deterministically from `seed_base`.
async def _b1_factory(*, setup: dict, seed_base: int, concurrency: int):
    worker_url = setup["worker_url"]
    corpus = setup["corpus"]
    n = len(corpus)

    client = httpx.AsyncClient(
        timeout=SNIPPET_TIMEOUT * 3,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )
    rng = random.Random(seed_base)
    # Per-child counters; the parent aggregates `counters` across procs.
    state = {"i": 0, "passes": 0}

    async def work_fn() -> dict:
        i = state["i"]
        state["i"] += 1
        # Mix in this child's seed so different procs traverse the
        # same corpus in different orders - prevents two procs from
        # synchronising on the same expensive HumanEval problem.
        idx = (rng.randrange(n) + i) % n
        code = corpus[idx]

        t0 = time.perf_counter()
        r = await client.post(
            f"{worker_url}/run",
            json={"code": code, "timeout": SNIPPET_TIMEOUT},
        )
        r.raise_for_status()
        wall_ms = (time.perf_counter() - t0) * 1000.0
        passed = 0
        try:
            if r.json().get("exit_code") == 0:
                passed = 1
                state["passes"] += 1
        except Exception:
            pass
        return {
            "wall_ms": wall_ms,
            "counters": {"passes": passed},
        }

    async def teardown():
        await client.aclose()

    return work_fn, teardown


class B1Runner(Runner):
    name = "B1"
    workload = "codeexec"

    def __init__(self) -> None:
        self._corpus, self._breakdown = load_corpus()
        # Shuffle once per process so different concurrency runs see the
        # same sequence (for comparability) but workers within a run
        # don't synchronize on the same problem at the same wall time.
        random.Random(42).shuffle(self._corpus)

    async def warmup(self, cfg: Config) -> None:
        url = f"{cfg.b1_worker_url}/healthz"
        async with httpx.AsyncClient(timeout=5.0) as c:
            for _ in range(30):
                try:
                    r = await c.get(url)
                    if r.status_code == 200:
                        return
                except Exception:
                    pass
                await asyncio.sleep(1)
        raise RuntimeError("b1 worker did not become ready")

    async def run_one(self, cfg: Config, instance: dict, concurrency: int) -> BenchmarkResult:
        sampler = ResourceSampler()
        sampler.start()
        reset_task = schedule_sampler_reset(sampler, cfg.warmup_sec, name=self.name)

        setup = {
            "worker_url": cfg.b1_worker_url,
            "corpus": self._corpus,
        }

        log.info("[B1] warmup=%ds + measure=%ds @ concurrency=%d",
                 cfg.warmup_sec, cfg.duration_sec, concurrency)

        try:
            mp_result = await drive_load_mp(
                work_factory=_b1_factory,
                setup=setup,
                concurrency=concurrency,
                duration_sec=cfg.duration_sec,
                warmup_sec=cfg.warmup_sec,
                nprocs=cfg.client_nprocs or None,
                seed_base=0xB1 ^ concurrency,
            )
        finally:
            if reset_task is not None and not reset_task.done():
                reset_task.cancel()
                try:
                    await reset_task
                except (asyncio.CancelledError, Exception):
                    pass
            res = await sampler.stop()

        ops = mp_result["completed"]
        tps = ops / cfg.duration_sec
        passes = mp_result["counters"].get("passes", 0)
        pass_rate = (passes / ops) if ops else 0.0

        return BenchmarkResult(
            benchmark=self.name,
            instance=instance,
            concurrency=concurrency,
            duration_sec=cfg.duration_sec,
            throughput={"executions_per_sec": tps, "total_ops": ops},
            latency_ms=mp_result["latency_ms"],
            resource=res,
            cost=cost_block(tps, cfg.duration_sec, instance["instance_type"], cfg),
            extra={
                "corpus_size": len(self._corpus),
                "corpus_breakdown": self._breakdown,
                "snippet_timeout_sec": SNIPPET_TIMEOUT,
                "pass_rate": round(pass_rate, 4),
                "load_gen": {
                    "nprocs": mp_result["nprocs"],
                    "concurrency_per_proc": mp_result["concurrency_per_proc"],
                },
            },
        )
