"""B3 - Tool/API call simulation (τ-bench-style).

Each "op" is one *trajectory* - a multi-step sequence of HTTP calls
against the b3-mock-api worker. Trajectories are sampled at random
from a pre-materialized pool built from 7 templates inspired by
tau-bench retail tasks (browse_only, buy_simple, buy_with_compare,
refund_flow, inventory_heavy, checkout_loop, profile_admin).

Load is generated by N child processes (one per orchestrator vCPU
by default) so a single asyncio event loop never becomes the
bottleneck - critical because each request is sub-millisecond and
the mock API can otherwise serve far more RPS than one Python
process can issue.
"""

from __future__ import annotations

import asyncio
import logging
import random
import time

import httpx

from config import Config
from metrics import LatencySink, ResourceSampler
from .b3_trajectories import build_trajectories
from .base import BenchmarkResult, Runner, cost_block
from .multiproc import drive_load_mp

log = logging.getLogger(__name__)


# Module-level worker factory - must be picklable for multi-process
# spawn to work. The setup dict carries everything the child needs
# to bootstrap its httpx client without touching parent state.
async def _b3_factory(*, setup: dict, seed_base: int, concurrency: int):
    base_url = setup["base_url"]
    trajectories = setup["trajectories"]  # list[(template, steps)]
    n = len(trajectories)

    client = httpx.AsyncClient(
        base_url=base_url,
        timeout=10.0,
        limits=httpx.Limits(
            max_connections=concurrency * 4,
            max_keepalive_connections=concurrency * 4,
        ),
    )
    rng = random.Random(seed_base)

    async def work_fn() -> float:
        steps = trajectories[rng.randrange(n)][1]
        t0 = time.perf_counter()
        for method, path, body in steps:
            if method == "GET":
                r = await client.get(path, params=body)
            else:
                r = await client.post(path, json=body)
            r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    async def teardown():
        await client.aclose()

    return work_fn, teardown


class B3Runner(Runner):
    name = "B3"
    workload = "toolcall"

    def __init__(self) -> None:
        self._trajectories, self._breakdown = build_trajectories(
            target_total=200, seed=42,
        )
        # Flatten Trajectory dataclass to plain tuples so it pickles
        # without dragging the dataclass module across processes.
        self._traj_flat = [
            (t.template, [(m, p, b) for (m, p, b) in t.steps])
            for t in self._trajectories
        ]

    async def warmup(self, cfg: Config) -> None:
        async with httpx.AsyncClient(timeout=5.0) as c:
            for _ in range(30):
                try:
                    r = await c.get(f"{cfg.b3_api_url}/healthz")
                    if r.status_code == 200:
                        return
                except Exception:
                    pass
                await asyncio.sleep(1)
        raise RuntimeError("b3 mock-api did not become ready")

    async def run_one(self, cfg: Config, instance: dict, concurrency: int) -> BenchmarkResult:
        sampler = ResourceSampler()
        sampler.start()

        setup = {
            "base_url": cfg.b3_api_url,
            "trajectories": self._traj_flat,
        }

        try:
            mp_result = await drive_load_mp(
                work_factory=_b3_factory,
                setup=setup,
                concurrency=concurrency,
                duration_sec=cfg.duration_sec,
                nprocs=cfg.client_nprocs or None,
                seed_base=0xB3 ^ concurrency,
            )
        finally:
            res = await sampler.stop()

        ops = mp_result["completed"]
        traj_per_sec = ops / cfg.duration_sec
        avg_steps = (
            sum(len(t[1]) for t in self._traj_flat) / len(self._traj_flat)
        )
        calls_per_sec = traj_per_sec * avg_steps

        return BenchmarkResult(
            benchmark=self.name,
            instance=instance,
            concurrency=concurrency,
            duration_sec=cfg.duration_sec,
            throughput={
                "trajectories_per_sec": traj_per_sec,
                "tool_calls_per_sec": calls_per_sec,
                "total_trajectories": ops,
                "total_tool_calls": int(ops * avg_steps),
            },
            latency_ms={
                "trajectory": mp_result["latency_ms"],
            },
            resource=res,
            cost=cost_block(traj_per_sec, cfg.duration_sec, instance["instance_type"], cfg),
            extra={
                "trajectory_pool_size": len(self._traj_flat),
                "trajectory_breakdown": self._breakdown,
                "avg_steps_per_trajectory": round(avg_steps, 2),
                "load_gen": {
                    "nprocs": mp_result["nprocs"],
                    "concurrency_per_proc": mp_result["concurrency_per_proc"],
                },
            },
        )
