"""B7 - text-game simulation (ALFWorld / TextWorld-style).

Each "op" is one HTTP request that asks the b7-textgame worker to
play `EPISODES_PER_REQUEST` mini-episodes back-to-back. The
simulator is a hand-rolled minigrid world (8 rooms, 30 items,
6 goal templates) - the original B7 design explicitly says we
measure "scheduling + GIL + tight Python loops", not ALFWorld's
task-completion accuracy, so a pure-Python equivalent gives the
same signal without the heavy native deps.

Load is generated by N child processes (one per orchestrator vCPU
by default) so a single asyncio event loop never becomes the
bottleneck - episodes are sub-millisecond each, so without
multi-process fan-out the orchestrator caps at ~1 core.
"""

from __future__ import annotations

import asyncio
import logging
import random
import time

import httpx

from config import Config
from metrics import ResourceSampler
from .base import BenchmarkResult, Runner, cost_block, schedule_sampler_reset
from .multiproc import drive_load_mp

log = logging.getLogger(__name__)

EPISODE_MIN = 30
EPISODE_MAX = 50
# Episodes per HTTP request. Sub-millisecond per-episode work would
# otherwise be drowned out by HTTP / FastAPI dispatch noise; batching
# brings each call into the few-ms range where the GIL + Python loop
# signal dominates - matching the original B7 design intent.
EPISODES_PER_REQUEST = 10


# Module-level worker factory - must be picklable for spawn-based mp.
async def _b7_factory(*, setup: dict, seed_base: int, concurrency: int):
    base_url = setup["base_url"]
    url = f"{base_url}/episode"
    client = httpx.AsyncClient(
        timeout=30.0,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )
    rng = random.Random(seed_base)

    async def work_fn() -> dict:
        steps = rng.randint(EPISODE_MIN, EPISODE_MAX)
        t0 = time.perf_counter()
        r = await client.post(url, json={
            "seed": rng.randrange(1 << 30),
            "steps": steps,
            "batch": EPISODES_PER_REQUEST,
        })
        r.raise_for_status()
        wall = (time.perf_counter() - t0) * 1000.0
        data = r.json()
        return {
            "wall_ms": wall,
            "counters": {
                "steps_total": data.get("steps_done", 0),
                "reward_total": data.get("total_reward", 0.0),
            },
        }

    async def teardown():
        await client.aclose()

    return work_fn, teardown


class B7Runner(Runner):
    name = "B7"
    workload = "textgame"

    async def warmup(self, cfg: Config) -> None:
        url = f"{cfg.b7_worker_url}/healthz"
        async with httpx.AsyncClient(timeout=5.0) as c:
            for _ in range(60):
                try:
                    r = await c.get(url)
                    if r.status_code == 200 and r.json().get("ok"):
                        return
                except Exception:
                    pass
                await asyncio.sleep(1)
        raise RuntimeError("b7 textgame worker did not become ready")

    async def run_one(
        self, cfg: Config, instance: dict, concurrency: int
    ) -> BenchmarkResult:
        sampler = ResourceSampler()
        sampler.start()

        reset_task = schedule_sampler_reset(sampler, cfg.warmup_sec, name=self.name)

        log.info("[B7] warmup=%ds + measure=%ds @ concurrency=%d",
                 cfg.warmup_sec, cfg.duration_sec, concurrency)

        try:
            mp_result = await drive_load_mp(
                work_factory=_b7_factory,
                setup={"base_url": cfg.b7_worker_url},
                concurrency=concurrency,
                duration_sec=cfg.duration_sec,
                warmup_sec=cfg.warmup_sec,
                nprocs=cfg.client_nprocs or None,
                seed_base=0xB7 ^ concurrency,
            )
        finally:
            if reset_task is not None and not reset_task.done():
                reset_task.cancel()
                try:
                    await reset_task
                except (asyncio.CancelledError, Exception):
                    pass
            res = await sampler.stop()

        ops = mp_result["completed"]
        steps_total = int(mp_result["counters"].get("steps_total", 0))
        reward_total = float(mp_result["counters"].get("reward_total", 0.0))

        episodes_done = ops * EPISODES_PER_REQUEST
        episodes_per_sec = episodes_done / cfg.duration_sec
        steps_per_sec = steps_total / cfg.duration_sec
        avg_steps = (steps_total / episodes_done) if episodes_done else 0.0
        avg_reward = (reward_total / episodes_done) if episodes_done else 0.0

        return BenchmarkResult(
            benchmark=self.name,
            instance=instance,
            concurrency=concurrency,
            duration_sec=cfg.duration_sec,
            throughput={
                "episodes_per_sec": episodes_per_sec,
                "steps_per_sec": steps_per_sec,
                "requests_per_sec": ops / cfg.duration_sec,
                "total_episodes": episodes_done,
                "total_steps": steps_total,
            },
            latency_ms=mp_result["latency_ms"],
            resource=res,
            cost=cost_block(episodes_per_sec, cfg.duration_sec, instance["instance_type"], cfg),
            extra={
                "episode_steps_range": [EPISODE_MIN, EPISODE_MAX],
                "episodes_per_request": EPISODES_PER_REQUEST,
                "avg_steps_per_episode": round(avg_steps, 2),
                "avg_reward_per_episode": round(avg_reward, 4),
                "world_rooms": 8,
                "world_items": 30,
                "goal_templates": 6,
                "load_gen": {
                    "nprocs": mp_result["nprocs"],
                    "concurrency_per_proc": mp_result["concurrency_per_proc"],
                },
            },
        )
