"""B9 - Concurrent end-to-end rollouts.

Simulates an RL trainer dispatching many rollouts in parallel to a
sandbox cluster. Each "rollout" is a mini-episode of 10..30 ops
where each op is sampled from a weighted task mix:

    B3 (tool-call trajectory)   weight 0.60
    B1 (python code execution)  weight 0.25
    B5 (DuckDB TPC-H query)     weight 0.15

A rollout completes when all its ops have returned successfully.
Throughput is reported as `rollouts_per_sec`; latency is the full
rollout wall time. Per-task latency channels are also reported so
the report can show which underlying sandbox dominates the long tail.

The signal vs running B1/B3/B5 in isolation is **long-tail
amplification**: one slow op in a rollout drags the whole rollout's
wall time, exactly like an RL synchronous batch waits for the
slowest sandbox.

Load is generated by N child processes (one per orchestrator vCPU
by default) so a single asyncio loop never becomes the bottleneck.
At concurrency 1024+ a single loop would bottleneck before the
worker fleet does.
"""

from __future__ import annotations

import asyncio
import logging
import random
import time

import httpx

from config import Config
from metrics import ResourceSampler
from .b1_corpus import load_corpus
from .b3_trajectories import build_trajectories as build_b3_trajectories
from .base import BenchmarkResult, Runner, cost_block, schedule_sampler_reset
from .multiproc import drive_load_mp

log = logging.getLogger(__name__)

# Task mix - weights determine sampling probability per op.
TASK_MIX = [
    ("B3", 0.60),
    ("B1", 0.25),
    ("B5", 0.15),
]

EPISODE_MIN_STEPS = 10
EPISODE_MAX_STEPS = 30

TPCH_QUERIES = list(range(1, 23))


# ---------------------------------------------------------------
# Picklable worker factory
# ---------------------------------------------------------------
async def _b9_factory(*, setup: dict, seed_base: int, concurrency: int):
    b1_url = setup["b1_worker_url"]
    b3_url = setup["b3_api_url"]
    b5_url = setup["b5_worker_url"]
    b1_corpus = setup["b1_corpus"]              # list[str]
    b3_trajs = setup["b3_trajectories"]         # list[(template, steps)]

    cum = setup["task_cum"]                     # cumulative weight list
    names = setup["task_names"]
    cum_total = setup["task_total"]

    b1_client = httpx.AsyncClient(
        timeout=60.0,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )
    b3_client = httpx.AsyncClient(
        base_url=b3_url,
        timeout=60.0,
        limits=httpx.Limits(max_connections=concurrency * 4),
    )
    b5_client = httpx.AsyncClient(
        timeout=600.0,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )
    rng = random.Random(seed_base)

    n_b1 = len(b1_corpus)
    n_b3 = len(b3_trajs)
    n_q = len(TPCH_QUERIES)

    def _pick_task() -> str:
        x = rng.random() * cum_total
        for nm, c in zip(names, cum):
            if x < c:
                return nm
        return names[-1]

    async def _do_b1() -> float:
        code = b1_corpus[rng.randrange(n_b1)]
        t0 = time.perf_counter()
        r = await b1_client.post(
            f"{b1_url}/run",
            json={"code": code, "timeout": 10},
        )
        r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    async def _do_b3() -> float:
        steps = b3_trajs[rng.randrange(n_b3)][1]
        t0 = time.perf_counter()
        for method, path, body in steps:
            if method == "GET":
                r = await b3_client.get(path, params=body)
            else:
                r = await b3_client.post(path, json=body)
            r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    async def _do_b5() -> float:
        q = TPCH_QUERIES[rng.randrange(n_q)]
        t0 = time.perf_counter()
        r = await b5_client.post(f"{b5_url}/query", json={"q": q})
        r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    dispatch = {"B1": _do_b1, "B3": _do_b3, "B5": _do_b5}

    async def work_fn() -> dict:
        n_steps = rng.randint(EPISODE_MIN_STEPS, EPISODE_MAX_STEPS)
        t0 = time.perf_counter()
        counters = {"steps_total": n_steps,
                    "ops_B1": 0, "ops_B3": 0, "ops_B5": 0}
        # Collect every per-task latency in this rollout so the parent
        # can build a real distribution per sub-task.
        ch_b1: list[float] = []
        ch_b3: list[float] = []
        ch_b5: list[float] = []
        buckets = {"B1": ch_b1, "B3": ch_b3, "B5": ch_b5}
        for _ in range(n_steps):
            task = _pick_task()
            lat = await dispatch[task]()
            counters[f"ops_{task}"] += 1
            buckets[task].append(lat)
        return {
            "wall_ms": (time.perf_counter() - t0) * 1000.0,
            "counters": counters,
            "channels": {
                "task_B1": ch_b1,
                "task_B3": ch_b3,
                "task_B5": ch_b5,
            },
        }

    async def teardown():
        await b1_client.aclose()
        await b3_client.aclose()
        await b5_client.aclose()

    return work_fn, teardown


class B9Runner(Runner):
    name = "B9"
    workload = "concurrent"

    def __init__(self) -> None:
        b1_corpus, _ = load_corpus()
        b3_trajs, _ = build_b3_trajectories(target_total=200, seed=93)
        # Pre-compute cumulative weights so the child process doesn't
        # have to recompute them on every step.
        names = [t for t, _ in TASK_MIX]
        weights = [w for _, w in TASK_MIX]
        cum: list[float] = []
        s = 0.0
        for w in weights:
            s += w
            cum.append(s)
        self._setup = {
            "b1_corpus": b1_corpus,
            "b3_trajectories": [
                (t.template, [(m, p, b) for (m, p, b) in t.steps])
                for t in b3_trajs
            ],
            "task_names": names,
            "task_cum": cum,
            "task_total": s,
        }

    async def warmup(self, cfg: Config) -> None:
        urls = [
            ("b1", f"{cfg.b1_worker_url}/healthz"),
            ("b3", f"{cfg.b3_api_url}/healthz"),
            ("b5", f"{cfg.b5_worker_url}/healthz"),
        ]
        async with httpx.AsyncClient(timeout=10.0) as c:
            for name, url in urls:
                ok = False
                for _ in range(180):
                    try:
                        r = await c.get(url)
                        if r.status_code == 200:
                            data = r.json() if r.headers.get("content-type", "").startswith("application/json") else {}
                            if data.get("ok", True):
                                ok = True
                                break
                    except Exception:
                        pass
                    await asyncio.sleep(1)
                if not ok:
                    raise RuntimeError(f"B9 dependency {name} not ready at {url}")

    async def run_one(
        self, cfg: Config, instance: dict, concurrency: int
    ) -> BenchmarkResult:
        sampler = ResourceSampler()
        sampler.start()

        # B9 has its own duration knob (defaults to 1800s = 30min).
        duration = cfg.b9_duration_sec or cfg.duration_sec

        reset_task = schedule_sampler_reset(sampler, cfg.warmup_sec, name=self.name)

        # Inject the per-run setup bundle (URLs come from cfg, can't be
        # captured in __init__ since the runner is built at import time).
        setup = dict(self._setup)
        setup.update({
            "b1_worker_url": cfg.b1_worker_url,
            "b3_api_url": cfg.b3_api_url,
            "b5_worker_url": cfg.b5_worker_url,
        })

        log.info("[B9] warmup=%ds + measure=%ds @ concurrency=%d",
                 cfg.warmup_sec, duration, concurrency)

        try:
            mp_result = await drive_load_mp(
                work_factory=_b9_factory,
                setup=setup,
                concurrency=concurrency,
                duration_sec=duration,
                warmup_sec=cfg.warmup_sec,
                nprocs=cfg.client_nprocs or None,
                seed_base=0xB9 ^ concurrency,
            )
        finally:
            if reset_task is not None and not reset_task.done():
                reset_task.cancel()
                try:
                    await reset_task
                except (asyncio.CancelledError, Exception):
                    pass
            res = await sampler.stop()

        ops = mp_result["completed"]
        counters = mp_result["counters"]
        steps_total = int(counters.get("steps_total", 0))
        rollouts_per_sec = ops / duration
        steps_per_sec = steps_total / duration
        avg_steps = (steps_total / ops) if ops else 0.0

        # Build per-task latency block from named channels.
        per_task = {}
        for tname in ("B1", "B3", "B5"):
            ch = mp_result["channels"].get(f"task_{tname}")
            if ch:
                per_task[tname] = {
                    "ops": int(counters.get(f"ops_{tname}", 0)),
                    **{k: ch[k] for k in ("count", "p50", "p95", "p99", "mean", "max")},
                }

        return BenchmarkResult(
            benchmark=self.name,
            instance=instance,
            concurrency=concurrency,
            duration_sec=duration,
            throughput={
                "rollouts_per_sec": rollouts_per_sec,
                "steps_per_sec": steps_per_sec,
                "total_rollouts": ops,
                "total_steps": steps_total,
            },
            latency_ms={
                "rollout": mp_result["latency_ms"],
                "per_task": per_task,
            },
            resource=res,
            cost=cost_block(rollouts_per_sec, duration, instance["instance_type"], cfg),
            extra={
                "task_mix": dict(TASK_MIX),
                "episode_steps_range": [EPISODE_MIN_STEPS, EPISODE_MAX_STEPS],
                "avg_steps_per_rollout": round(avg_steps, 2),
                "ops_breakdown": {
                    "B1": int(counters.get("ops_B1", 0)),
                    "B3": int(counters.get("ops_B3", 0)),
                    "B5": int(counters.get("ops_B5", 0)),
                },
                "load_gen": {
                    "nprocs": mp_result["nprocs"],
                    "concurrency_per_proc": mp_result["concurrency_per_proc"],
                },
            },
        )
