"""B9 - Concurrent end-to-end rollouts.

Simulates an RL trainer dispatching many rollouts in parallel to a
sandbox cluster. Each "rollout" is a mini-episode of 10..30 ops
where each op is sampled from a weighted task mix:

    B3 (tool-call trajectory)        weight 0.50
    B1 (python code execution)       weight 0.20
    B5 (DuckDB TPC-H query)          weight 0.10
    B4 (browser trajectory)          weight 0.10
    B7 (text-game episode batch)     weight 0.10

A rollout completes when all its ops have returned successfully.
Throughput is reported as `rollouts_per_sec`; latency is the full
rollout wall time. Per-task latency channels are also reported so
the report can show which underlying sandbox dominates the long tail.

The signal vs running B1/B3/B4/B5/B7 in isolation is **long-tail
amplification**: one slow op in a rollout drags the whole rollout's
wall time, exactly like an RL synchronous batch waits for the
slowest sandbox. B4 (browser) adds a particularly heavy tail since
its op latency is 1-2 orders of magnitude above the others, so its
share of the mix dominates p99 even at 10% weight.

Load is generated by N child processes (one per orchestrator vCPU
by default) so a single asyncio loop never becomes the bottleneck.
At concurrency 1024+ a single loop would bottleneck before the
worker fleet does.
"""

from __future__ import annotations

import asyncio
import logging
import random
import time

import httpx

from config import Config
from metrics import ResourceSampler
from .b1_corpus import load_corpus
from .b3_trajectories import build_trajectories as build_b3_trajectories
from .b4_trajectories import build_trajectories as build_b4_trajectories
from .base import BenchmarkResult, Runner, cost_block, schedule_sampler_reset
from .multiproc import drive_load_mp

log = logging.getLogger(__name__)

# Task mix - weights determine sampling probability per op.
# B4 / B7 deliberately get a smaller share than their wall-time would
# suggest, otherwise their slow ops monopolise every rollout and the
# faster sandboxes (B1/B3/B5) never get exercised.
TASK_MIX = [
    ("B3", 0.50),   # ~5-15ms per trajectory
    ("B1", 0.20),   # ~50-80ms per code-exec
    ("B5", 0.10),   # ~50ms-5s per TPC-H query
    ("B4", 0.10),   # ~1-3s per browser trajectory
    ("B7", 0.10),   # ~5-50ms per episode batch
]

EPISODE_MIN_STEPS = 10
EPISODE_MAX_STEPS = 30

TPCH_QUERIES = list(range(1, 23))

# B7 episode parameters - mirror b7_textgame.py defaults.
B7_EPISODE_MIN = 30
B7_EPISODE_MAX = 50
B7_EPISODES_PER_REQUEST = 10


# ---------------------------------------------------------------
# Picklable worker factory
# ---------------------------------------------------------------
async def _b9_factory(*, setup: dict, seed_base: int, concurrency: int):
    b1_url = setup["b1_worker_url"]
    b3_url = setup["b3_api_url"]
    b4_url = setup["b4_worker_url"]
    b4_target = setup["b4_target_url"]
    b5_url = setup["b5_worker_url"]
    b7_url = setup["b7_worker_url"]
    b1_corpus = setup["b1_corpus"]              # list[str]
    b3_trajs = setup["b3_trajectories"]         # list[(template, steps)]
    b4_trajs = setup["b4_trajectories"]         # list[(template, list[step_dict])]

    cum = setup["task_cum"]                     # cumulative weight list
    names = setup["task_names"]
    cum_total = setup["task_total"]

    # Per-downstream client. Each tuned for its own latency profile:
    #   - b1: subprocess fork, ~80ms typical, can spike on fork-storm
    #   - b3: in-mem dict, sub-millisecond, large keepalive pool
    #   - b4: chromium IPC, multi-second; long timeout, small pool
    #   - b5: DuckDB TPC-H, can take seconds for heavy queries
    #   - b7: pure-python sim, tens of milliseconds
    b1_client = httpx.AsyncClient(
        timeout=60.0,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )
    b3_client = httpx.AsyncClient(
        base_url=b3_url,
        timeout=60.0,
        limits=httpx.Limits(max_connections=concurrency * 4),
    )
    # B4 uses Connection: close + no keepalive to bypass the kernel
    # SO_REUSEPORT imbalance we documented in b4_browser.py.
    b4_client = httpx.AsyncClient(
        timeout=180.0,
        limits=httpx.Limits(
            max_connections=concurrency * 2,
            max_keepalive_connections=0,
        ),
        headers={"Connection": "close"},
    )
    b5_client = httpx.AsyncClient(
        timeout=600.0,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )
    b7_client = httpx.AsyncClient(
        timeout=30.0,
        limits=httpx.Limits(max_connections=concurrency * 2),
    )

    rng = random.Random(seed_base)

    n_b1 = len(b1_corpus)
    n_b3 = len(b3_trajs)
    n_b4 = len(b4_trajs)
    n_q = len(TPCH_QUERIES)

    # Discover B4 worker ports for client-side round-robin (B4 launches
    # one uvicorn process per port; SO_REUSEPORT alone is too uneven on
    # aarch64 for B4 specifically). If discovery fails (older B4 image
    # or transient error), we fall back to a single URL and accept the
    # imbalance - same behaviour as B4 standalone.
    b4_urls = [b4_url]
    try:
        ports_resp = await b4_client.get(f"{b4_url}/ports")
        if ports_resp.status_code == 200:
            ports = ports_resp.json().get("ports", [])
            if ports:
                host = b4_url.split("://", 1)[-1].split(":", 1)[0]
                b4_urls = [f"http://{host}:{p}" for p in ports]
        if len(b4_urls) == 1:
            print(f"[b9] WARN seed={seed_base}: B4 ports discovery returned "
                  f"single URL; round-robin disabled, expect SO_REUSEPORT "
                  f"imbalance for B4 ops", flush=True)
    except Exception as e:
        print(f"[b9] WARN seed={seed_base}: B4 ports discovery failed "
              f"({e!r}); falling back to single URL", flush=True)

    def _pick_task() -> str:
        x = rng.random() * cum_total
        for nm, c in zip(names, cum):
            if x < c:
                return nm
        return names[-1]

    async def _do_b1() -> float:
        code = b1_corpus[rng.randrange(n_b1)]
        t0 = time.perf_counter()
        r = await b1_client.post(
            f"{b1_url}/run",
            json={"code": code, "timeout": 10},
        )
        r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    async def _do_b3() -> float:
        steps = b3_trajs[rng.randrange(n_b3)][1]
        t0 = time.perf_counter()
        for method, path, body in steps:
            if method == "GET":
                r = await b3_client.get(path, params=body)
            else:
                r = await b3_client.post(path, json=body)
            r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    # Round-robin counter for B4 worker ports. We use the rng to pick
    # a starting offset per child so multiple children don't all hit
    # the same port first.
    b4_counter = {"i": rng.randrange(len(b4_urls))}

    async def _do_b4() -> float:
        steps = b4_trajs[rng.randrange(n_b4)][1]
        idx = b4_counter["i"]
        b4_counter["i"] = idx + 1
        target = b4_urls[idx % len(b4_urls)]
        t0 = time.perf_counter()
        r = await b4_client.post(
            f"{target}/task",
            json={
                "target_url": b4_target,
                "steps": [
                    {"action": s["action"], "args": s.get("args", {})}
                    for s in steps
                ],
            },
        )
        r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    async def _do_b5() -> float:
        q = TPCH_QUERIES[rng.randrange(n_q)]
        t0 = time.perf_counter()
        r = await b5_client.post(f"{b5_url}/query", json={"q": q})
        r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    async def _do_b7() -> float:
        steps = rng.randint(B7_EPISODE_MIN, B7_EPISODE_MAX)
        t0 = time.perf_counter()
        r = await b7_client.post(
            f"{b7_url}/episode",
            json={
                "seed": rng.randrange(1 << 30),
                "steps": steps,
                "batch": B7_EPISODES_PER_REQUEST,
            },
        )
        r.raise_for_status()
        return (time.perf_counter() - t0) * 1000.0

    dispatch = {
        "B1": _do_b1, "B3": _do_b3, "B4": _do_b4,
        "B5": _do_b5, "B7": _do_b7,
    }

    async def work_fn() -> dict:
        n_steps = rng.randint(EPISODE_MIN_STEPS, EPISODE_MAX_STEPS)
        t0 = time.perf_counter()
        counters = {
            "steps_total": n_steps,
            "ops_B1": 0, "ops_B3": 0, "ops_B4": 0,
            "ops_B5": 0, "ops_B7": 0,
        }
        # Collect every per-task latency in this rollout so the parent
        # can build a real distribution per sub-task.
        ch = {"B1": [], "B3": [], "B4": [], "B5": [], "B7": []}
        for _ in range(n_steps):
            task = _pick_task()
            lat = await dispatch[task]()
            counters[f"ops_{task}"] += 1
            ch[task].append(lat)
        return {
            "wall_ms": (time.perf_counter() - t0) * 1000.0,
            "counters": counters,
            "channels": {f"task_{k}": v for k, v in ch.items()},
        }

    async def teardown():
        for c in (b1_client, b3_client, b4_client, b5_client, b7_client):
            try:
                await c.aclose()
            except Exception:
                pass

    return work_fn, teardown


class B9Runner(Runner):
    name = "B9"
    workload = "concurrent"

    def __init__(self) -> None:
        b1_corpus, _ = load_corpus()
        b3_trajs, _ = build_b3_trajectories(target_total=200, seed=93)
        b4_trajs, _ = build_b4_trajectories(target_total=80, seed=94)
        # Pre-compute cumulative weights so the child process doesn't
        # have to recompute them on every step.
        names = [t for t, _ in TASK_MIX]
        weights = [w for _, w in TASK_MIX]
        cum: list[float] = []
        s = 0.0
        for w in weights:
            s += w
            cum.append(s)
        self._setup = {
            "b1_corpus": b1_corpus,
            "b3_trajectories": [
                (t.template, [(m, p, b) for (m, p, b) in t.steps])
                for t in b3_trajs
            ],
            "b4_trajectories": [
                (t.template, list(t.steps)) for t in b4_trajs
            ],
            "task_names": names,
            "task_cum": cum,
            "task_total": s,
        }

    async def warmup(self, cfg: Config) -> None:
        urls = [
            ("b1", f"{cfg.b1_worker_url}/healthz"),
            ("b3", f"{cfg.b3_api_url}/healthz"),
            ("b4", f"{cfg.b4_worker_url}/healthz"),
            ("b5", f"{cfg.b5_worker_url}/healthz"),
            ("b7", f"{cfg.b7_worker_url}/healthz"),
        ]
        async with httpx.AsyncClient(timeout=10.0) as c:
            for name, url in urls:
                ok = False
                for _ in range(180):
                    try:
                        r = await c.get(url)
                        if r.status_code == 200:
                            data = r.json() if r.headers.get("content-type", "").startswith("application/json") else {}
                            if data.get("ok", True):
                                ok = True
                                break
                    except Exception:
                        pass
                    await asyncio.sleep(1)
                if not ok:
                    raise RuntimeError(f"B9 dependency {name} not ready at {url}")

    async def run_one(
        self, cfg: Config, instance: dict, concurrency: int
    ) -> BenchmarkResult:
        sampler = ResourceSampler()
        sampler.start()

        # B9 has its own duration knob (defaults to 1800s = 30min).
        duration = cfg.b9_duration_sec or cfg.duration_sec

        reset_task = schedule_sampler_reset(sampler, cfg.warmup_sec, name=self.name)

        # Inject the per-run setup bundle (URLs come from cfg, can't be
        # captured in __init__ since the runner is built at import time).
        setup = dict(self._setup)
        setup.update({
            "b1_worker_url": cfg.b1_worker_url,
            "b3_api_url": cfg.b3_api_url,
            "b4_worker_url": cfg.b4_worker_url,
            "b4_target_url": cfg.b4_target_url,
            "b5_worker_url": cfg.b5_worker_url,
            "b7_worker_url": cfg.b7_worker_url,
        })

        log.info("[B9] warmup=%ds + measure=%ds @ concurrency=%d",
                 cfg.warmup_sec, duration, concurrency)

        try:
            mp_result = await drive_load_mp(
                work_factory=_b9_factory,
                setup=setup,
                concurrency=concurrency,
                duration_sec=duration,
                warmup_sec=cfg.warmup_sec,
                nprocs=cfg.client_nprocs or None,
                seed_base=0xB9 ^ concurrency,
            )
        finally:
            if reset_task is not None and not reset_task.done():
                reset_task.cancel()
                try:
                    await reset_task
                except (asyncio.CancelledError, Exception):
                    pass
            res = await sampler.stop()

        ops = mp_result["completed"]
        counters = mp_result["counters"]
        steps_total = int(counters.get("steps_total", 0))
        rollouts_per_sec = ops / duration
        steps_per_sec = steps_total / duration
        avg_steps = (steps_total / ops) if ops else 0.0

        # Build per-task latency block from named channels.
        per_task = {}
        for tname in ("B1", "B3", "B4", "B5", "B7"):
            ch = mp_result["channels"].get(f"task_{tname}")
            if ch:
                per_task[tname] = {
                    "ops": int(counters.get(f"ops_{tname}", 0)),
                    **{k: ch[k] for k in ("count", "p50", "p95", "p99", "mean", "max")},
                }

        return BenchmarkResult(
            benchmark=self.name,
            instance=instance,
            concurrency=concurrency,
            duration_sec=duration,
            throughput={
                "rollouts_per_sec": rollouts_per_sec,
                "steps_per_sec": steps_per_sec,
                "total_rollouts": ops,
                "total_steps": steps_total,
            },
            latency_ms={
                "rollout": mp_result["latency_ms"],
                "per_task": per_task,
            },
            resource=res,
            cost=cost_block(rollouts_per_sec, duration, instance["instance_type"], cfg),
            extra={
                "task_mix": dict(TASK_MIX),
                "episode_steps_range": [EPISODE_MIN_STEPS, EPISODE_MAX_STEPS],
                "avg_steps_per_rollout": round(avg_steps, 2),
                "ops_breakdown": {
                    "B1": int(counters.get("ops_B1", 0)),
                    "B3": int(counters.get("ops_B3", 0)),
                    "B4": int(counters.get("ops_B4", 0)),
                    "B5": int(counters.get("ops_B5", 0)),
                    "B7": int(counters.get("ops_B7", 0)),
                },
                "load_gen": {
                    "nprocs": mp_result["nprocs"],
                    "concurrency_per_proc": mp_result["concurrency_per_proc"],
                },
            },
        )
